### ISSUE TITLE
unify accept loop and process accept in lwt (conduit_lwt_unix,conduit_lwt_tls, conduit_lwt_unix_ssl)

### ISSUE THREAD

**Issue by edwintorok** [mirage/ocaml-conduit#112]
bugfixes/changes would have to be applied 3 times otherwise, e.g. https://github.com/mirage/ocaml-conduit/pull/111
To avoid creating circular dependencies perhaps should be a `conduit_lwt.ml` for shared code.

**Comment by dinosaure** [comment]
From the new version of `conduit`, it seems that the only diff between what you did and the current implementation of the server loop is the use of `Lwt.cancel` on your side. You can see the impl. here:
https://github.com/mirage/ocaml-conduit/blob/66fd34a9dc1dc2507f6c20752e589ae53cc4ccf8/src/lwt/conduit_lwt.ml#L66-L81

Should we re-integrate `Lwt.cancel` @edwintorok?
