### ISSUE TITLE
Access to the socket file-descriptor

### ISSUE THREAD

**Issue by smondet** [mirage/ocaml-conduit#119]
It would be useful to be able to set socket options; or more generally to have access (also from cohttp) to the underliying `Lwt_unix.file_descr` that is used with `bind` and `listen`
(like here: https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_unix.ml#L198)

PS: my use-case is about adding `Lwt_unix.set_close_on_exec`, if people think it's useful I can create a PR that adds it to all the "listening" file-descriptors.

**Comment by dinosaure** [comment]
According to the new version of `conduit`, we are able now (4 years after) to destruct the `Conduit.flow` to the underlying used value such as:
```ocaml
Conduit_lwt.resolve ~resolvers domain_name >>= function
| Ok (Conduit_lwt.TCP.T lwt_socket) -> ...
| _ -> ...
```
