### ISSUE TITLE
Conduit_async.connect should be able to use an Uri as well as an IP

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-conduit#131]
Currently, I can't use it because I have an Uri and I don't want to resolve it myself.

**Comment by dinosaure** [comment]
A decision about the new design of `conduit` was to not use `Uri.t` as the concrete type to resolve which connection we want (see #310). We replaced that by an `[ host ] Domain_name.t` and #322 will extend it with IP. This issue highlighted an other problem where previous version of `conduit-async` and `conduit-lwt` was not really homogenized into a common interface - this is the case now.

From my perspective, if you really want to use an `Uri.t` as the concrete type for the resolution, you should be able to do that with another higher library (on top of `conduit`). I will close this issue as a an unrelated issue with the new version of `conduit`.
