### ISSUE TITLE
Conduit need a lot of RAM to build

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-conduit#135]
1Go is not enough. Even core and async compile fine with this amount of RAM. Why?

**Comment by avsm** [comment]
What options are you building with?  Does this only trigger on the Async backend by any chance?

**Comment by vbmithr** [comment]
On 18/07/2016 23:02, Anil Madhavapeddy wrote:
> What options are you building with? Does this only trigger on the Async
> backend by any chance?

I'm indeed using Async. I'm gonna check if it changes anything on Lwt. I
think this is because the build system uses 2 threads by default, while
the other packages I compiled are only compiled sequentially.

-- 
Vincent

**Comment by avsm** [comment]
yes could be concurrent builds pushing you over.  on ARM?

**Comment by vbmithr** [comment]
On 18/07/2016 23:26, Anil Madhavapeddy wrote:
> yes could be concurrent builds pushing you over. on ARM?

On an EC2 micro instance.

-- 
Vincent
