### ISSUE TITLE
mirage resolver fails with "name resolution failed" when given ip:port based uri

### ISSUE THREAD

**Issue by sevenEng** [mirage/ocaml-conduit#140]
This may be one of the corner cases, but I tried issuing HTTP requests using ip:port generated uri.

While targeting to unix and using `resolver_unix_system` everything works fine, but switching to xen and [resolver_dns](https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L949) gives

```
Fatal error: exception (Failure "name resolution failed: unknown endpoint type") 
```

I think this exception comes from this function: [dns_stub_resolver](https://github.com/mirage/ocaml-conduit/blob/master/lib/resolver_mirage.ml#L109). Before referring to `DNS.gethostbyname`, if the host part of uri is an ip address, maybe we could just return it and the port. If this is the case, I could submit a patch later.

**Comment by yomimono** [comment]
Fixed by the reporter in #145 - thanks again @sevenEng !
