### ISSUE TITLE
Handle failed lwt threads in server

### ISSUE THREAD

**Issue by copy** [mirage/ocaml-conduit#141]
Currently failing lwt threads are swallowed (I checked `Conduit_lwt_unix.serve`, but maybe there are other places). I think the error should be reported somehow, or at least this behaviour should be documented. See example below.

```ocaml
let () =
  let ctx = Conduit_lwt_unix.default_ctx in
  let mode = `TCP (`Port 1234) in
  let main = Conduit_lwt_unix.serve ~ctx ~mode (fun flow ic oc -> Lwt.fail_with "oh no") in
  Lwt_main.run main
```

**Comment by vbmithr** [comment]
Hey,

I'm not using the Lwt backend anymore but I agree that failing threads
should never be swallowed. Feel free to push a PR fixing this. Thanks.

**Comment by avsm** [comment]
Right, Lwt really needs some sort of Monitor-style library where errors can be dispatched too. Another option is to use [Logs](http://erratique.ch/software/logs) to record them.

**Comment by rgrinberg** [comment]
Easiest approach would be to follow the async style of providing an error callback to the server. See `on_handler_error`.

**Comment by copy** [comment]
> Easiest approach would be to follow the async style of providing an error callback to the server. See on_handler_error.

I think an easier approach would be to follow the strategy of `Lwt_io.establish_server_safe` and pass all errors to `Lwt.async_exception_hook`, so the caller can wrap the callback into `Lwt.catch` themself.

**Comment by SGrondin** [comment]
Thank you @copy for https://github.com/mirage/ocaml-conduit/pull/143/files . I'm eagerly waiting for it to be merged into master. In the mean time I'm using it in my fork.
