### ISSUE TITLE
TLS authentication trust anchors

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-conduit#147]
should default to exceptional behaviour (empty trust anchors), instead of not validating the certificate chain, see https://github.com/mirage/ocaml-conduit/blob/78b113fab909f8369a5b5c5fe1fe9c12be3c32a0/lib/conduit_lwt_tls.ml#L31 and likely similar cases for other front/backends; further discussion at https://github.com/mirage/ocaml-cohttp/issues/479#issuecomment-217809202

**Comment by dinosaure** [comment]
I think this issue is a duplicate with https://github.com/mirage/ocaml-conduit/issues/31#issuecomment-701348537 - so I close this issue.
