### ISSUE TITLE
Development very annoying due to ppx

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-conduit#152]
Using my editor, I can't jump to errors because the file referenced is the temporary source file generated by the ppx extension. We should really fix this :(

**Comment by rgrinberg** [comment]
While I sympathize, I don't think there's much we can apart from removing ppx_optcomp. I don't know if that's possible but I somehow doubt it. Refactoring stuff that doesn't need optcomp into its own modules would be nice though.

**Comment by Drup** [comment]
`ppx_optcomp` doesn't use line directives .. ?!

**Comment by vbmithr** [comment]
line directives?

**Comment by dbuenzli** [comment]
http://caml.inria.fr/pub/docs/manual-ocaml/lex.html#sec74

**Comment by rgrinberg** [comment]
Do these directives help with the cmt based definition lookup merlin has?

I'm not sure.

**Comment by avsm** [comment]
I'm taking a shot at replacing the use of ppx_optcomp with a dynamic registration mechanism using open types.  I think we can bump to 4.02 as a minimum version now without too much controversy...

**Comment by vbmithr** [comment]
On 10/10/2016 16:48, Anil Madhavapeddy wrote:
> I'm taking a shot at replacing the use of ppx_optcomp with a dynamic
> registration mechanism using open types. I think we can bump to 4.02 as
> a minimum version now without too much controversy...

+1

**Comment by rgrinberg** [comment]
It's already at 4.02.3 minimum because of ppx. So please save us from optcomp.

**Comment by rgrinberg** [comment]
@avsm Would you mind sharing a sketch of your registration using open types idea? Maybe me or @vbmithr might give it a stab.

**Comment by samoht** [comment]
Closing as there is no more ppx_optcomp
