### ISSUE TITLE
Conduit_mirage silently skips certificate validation

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-conduit#153]
config.ml:

```
open Mirage

let stackv4 = generic_stackv4 default_console tap0
let tls_conduit = conduit_direct ~tls:true stackv4
let main = foreign "Unikernel.Main" (resolver @-> conduit @-> job)

let () =
  register "client" [main $ resolver_dns stackv4 $ tls_conduit]
```

unikernel.ml:

```
open Lwt.Infix

let test_server = "https://example.com"
(* A web-site with a self-signed or otherwise untrusted X.509 certificate. *)

module Main(R : Resolver_lwt.S)(C : Conduit_mirage.S) = struct
  let start resolver conduit =
    R.resolve_uri resolver ~uri:(Uri.of_string test_server) >>= fun endp ->
(*     Logs.info (fun f -> f "Resolved to address: %s" (Sexplib.Std.string_of_sexp (Conduit.sexp_of_endp endp))); *)
    Conduit_mirage.client endp >>= fun client ->
    C.connect conduit client >>= fun flow ->
    Conduit_mirage.Flow.write flow (Cstruct.of_string "GET / HTTP/1.0\r\n\r\n") >>= function
    | `Eof | `Error _ -> assert false
    | `Ok () ->
      let rec loop () =
        Conduit_mirage.Flow.read flow >>= function
        | `Error _ -> failwith "Error!"
        | `Eof ->
          Logs.info (fun f -> f "End of file");
          Lwt.return_unit
        | `Ok data ->
          Logs.info (fun f -> f "Got: %s" (Cstruct.to_string data));
          loop ()
      in
      loop ()
end
```

Set `test_server` to a web server with a self-signed X.509 certificate (one that a web-brower would reject). Test with:

```
mirage configure --net=socket --no-opam
make
./main.native
```

Expected outcome:
- Conduit refuses to connect because site cannot be authenticated; OR
- The code does not compile because no authenticator is specified

Actual outcome:
- Conduit connects and returns the contents of the web-page

This is related to #31, but the bug here is that it silently disables the security check, which I think is a separate and more important issue than security checks not being available. i.e. this bug could be closed if it errored out instead of pretending to work.

(aside: the commented-out debug line for some reason crashes the process with `Failure "string_of_sexp: atom needed"`, but that's another bug...)

**Comment by hannesm** [comment]
see #147

**Comment by dinosaure** [comment]
Same as #147 and #31, see this comment: https://github.com/mirage/ocaml-conduit/issues/31#issuecomment-701348537.
