### ISSUE TITLE
Give access to TLS connection

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-conduit#155]
From this issue: https://github.com/mirage/ocaml-cohttp/issues/509, reading cohttp/conduit code led to post my problem here.

In a cohttp server, I need to access the TLS session (a [Tls_lwt.t](https://mirleft.github.io/ocaml-tls/Tls_lwt.Unix.html#TYPEt)). The `IO.conn` parameter of callback function of HTTP server (from Cohttp_lwt_unix_io) is a [Conduit_lwt_unix.flow](http://docs.mirage.io/odoc/conduit/Conduit_lwt_unix/index.html#/flow.typ). I can retrieve the file descriptor, since the flow is a `TCP` but I cannot retrieve the Tls session to perform operations on it.

I don't have a solution to make this TLS session available without changing the `Conduit_lwt_unix.flow` type, for example by adding a TLS constructor, something like:

``` ocaml
type flow =
 ...
| Tls of Tls_lwt.Unix.t * flow
```

**Comment by dinosaure** [comment]
As explained in this comment: https://github.com/mirage/ocaml-conduit/issues/119
The new version of `conduit` lets the user to destruct the `Conduit.flow` to what you want. In the case of `conduit-lwt-tls`, the code will be:
```ocaml
Conduit_lwt.resolve ~resolvers domain_name >>= function
| Ok (Conduit_lwt_tls.TCP.T v) ->
  let lwt_socket = Conduit_lwt_tls.underlying v in
  ...
| _ -> ...
