### ISSUE TITLE
More types of conduits

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-conduit#157]
There are many more types of conduits that the ones currently exposed by that library. That would be great to have a common home to put all of them together. See for instance https://github.com/docker/datakit/blob/master/src/datakit_conduit.ml which abstract socket listening over:
- Unix domain sockets
- HyperV sockets
- Windows named pipes

Currently `conduit` is not in shape to welcome this new backends as I am not very happy with the current API (note: I wrote parts of that API, so I am certainly to blame).  Would be great if we could have a better design using some new features of OCaml, such as open types. WDYT?

**Comment by avsm** [comment]
Yes, I'm working on a design that should obviate the current need for cppo and many of the functors, and this incorporates the feedback from @selipou's OCaml workshop talk on the webstack. Will update shortly.

**Comment by amirmc** [comment]
Wassim and Heikki at Ericsson may also have some feedback.  I believe they looked at conduit before using just vchan for their NFV platform.  I can't tag them here as I've no idea what their GitHub IDs are but maybe you could email the list about this?

**Comment by dinosaure** [comment]
The new version of `conduit` uses extensible variant to let the user to define its own type. 4 years after, we are able to close this PR :tada:.
