### ISSUE TITLE
Expose conduit destination

### ISSUE THREAD

**Issue by juanchanco** [mirage/ocaml-conduit#159]
As a security for a webservice I'm writing, I have to log the IP address of the requester. Unix conduit exposes this indirectly via sexp_of_flow, but for Mirage conduit, that information is hidden. It would be nice to have this available in a uniform way. There may be a need to change to more generally change behavior base on the remote endpoint (security, logging, quotas, etc).

I've attached a primitive implementation I threw together for my current projects, but it doesn't cover Vchan flows. (I've attached the specific files here as well).
https://github.com/juanchanco/ocaml-conduit/tree/Flow.get_dest

[files.zip](https://github.com/mirage/ocaml-conduit/files/548342/files.zip)

**Comment by dinosaure** [comment]
According to the new version of `conduit`, we are now able to introspect the current `Conduit.flow` value and get some information such as the endpoint. In your case, the code will be:
```ocaml
Conduit_lwt.resolve ~resolvers domain_name >>= function
| Ok (Conduit_lwt.TCP.T lwt_socket) ->
  let peer = Lwt_unix.getpeername lwt_socket in
  ...
| _ -> ...
