### ISSUE TITLE
tests are broken on debian unstable

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-conduit#165]
See https://travis-ci.org/mirage/ocaml-conduit/jobs/153205456#L1075 for an example.  Installing `ssl` fails consistently on debian unstable, so the test can't pass.  `ssl` issue tracker: https://github.com/savonet/ocaml-ssl/issues/26 .

**Comment by avsm** [comment]
it might be time to pull support for the C binding from Conduit...

**Comment by talex5** [comment]
That's odd: the fixed version was accepted into Debian on 3rd Nov. Maybe the `ocaml/opam:debian-unstable_ocaml-4.02.3` needs updating?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828462
https://tracker.debian.org/pkg/ocaml-ssl

**Comment by avsm** [comment]
It was updated this afternoon, so rerunning the test may help.

**Comment by yomimono** [comment]
Ah.  I last observed it 18 hours ago, so I'll re-run the test and close this if it passes.  Thanks!

**Comment by yomimono** [comment]
Still broken: https://travis-ci.org/mirage/ocaml-conduit/jobs/153205456#L1075

**Comment by yomimono** [comment]
Not still broken: https://travis-ci.org/mirage/ocaml-conduit/builds/180752799
