### ISSUE TITLE
conduit.mirage no longer being installed

### ISSUE THREAD

**Issue by juanchanco** [mirage/ocaml-conduit#188]
The 0.14.* series seems to no longer install conduit.mirage. As a result, installing mirage-conduit (via opam) fails. Is it no longer needed? Currently, mirage-conduit is a dependency for mirage-http.

**Comment by samoht** [comment]
My bad, I've merged changes in master which should have been merged with the `mirage-dev` branch instead. I am currently fixing this.

**Comment by juanchanco** [comment]
Everything works find with version 0.14.2 now, thanks.
