### ISSUE TITLE
Conduit silently ignores exceptions from handlers

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-conduit#204]
```
#require "conduit.lwt-unix";;

open Lwt.Infix

let () =
  Logs.set_reporter (Logs_fmt.reporter ())

let addr = Unix.ADDR_INET (Unix.inet_addr_loopback, 8080)

let callback _ =
  print_endline "In callback";
  Lwt.fail (Failure "An error!")

let () =
  Lwt_main.run begin
    Conduit_lwt_server.listen addr
    |> Conduit_lwt_server.init callback
  end
```

If you run this program and try to connect to `localhost:8080`, it prints `In callback` but the exception is not displayed.

I think the problem is here, in `Conduit_lwt_server`:

```
         | `Accept v ->
           Lwt.on_termination (handler v) disconnected;
           loop ()
```

`on_termination` will call `disconnected` if the handler fails, but will not report the error anywhere.

Also, if `callback` raises an exception without blocking (e.g. using `failwith` instead of `Lwt.fail`) then the server process exits prints the exception and then exits because the `Log.warn` doesn't call `loop`.

**Comment by talex5** [comment]
( I forgot to update the title before submitting - it was originally silently exiting because I hadn't configured Logs... so many ways to fail silently :-( )

**Comment by edwintorok** [comment]
Might be useful to distinguish between exceptions from `accept` and exceptions from `handler v`. For the latter it should definetely call `loop` again, not sure about `accept`: you can easily flood your logs if you run out of file descriptors, but thats what yield is supposed to mitigate there...
