### ISSUE TITLE
Using ocaml-tls by default broken after move to jbuilder

### ISSUE THREAD

**Issue by hcarty** [mirage/ocaml-conduit#233]
conduit used to use ocaml-tls without any environment variable(s) set if it was installed and ocaml-ssl was not.  This seems to no longer be the case in 1.0.0 (see https://github.com/mirage/ocaml-cohttp/issues/571).

What are appropriate steps to fix this?  Could there be a flag in `Conduit_lwt_tls` indicating if the module is the real or fake version, with this used to enable tls support if the environment variable isn't set?

**Comment by rgrinberg** [comment]
So I guess the conclusion here is that ocaml-tls should be the default tls backend when it's available. Am I understanding that right?

**Comment by hcarty** [comment]
That's what I would prefer and propose in #234

**Comment by samoht** [comment]
Yes please. This is an annoying regression which breaks all users of conduit+tls (for instance `opam-publish`).
