### ISSUE TITLE
Fatal error: exception (Failure "Ssl not available")

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-conduit#242]
I have `conduit-lwt-unix` (1.0.0) installed, and try to use the `ogit` binary provided by `git-unix` (1.11.2) [all using OCaml-4.04.2].

When executing `ogit clone https://github.com/hannesm/duration.git`, I receive an error `Fatal error: exception (Failure "Ssl not available")`

When I manually `setenv CONDUIT_TLS native` and rerun the command, it succeeds.

This seems to be a regression: I remember in earlier days the autodiscovery was done at compile time, and there shouldn't be a runtime error, since `conduit-lwt-unix` links a TLS implementation and could work appropriately.  Maybe this is related to recent build system changes?

**Comment by samoht** [comment]
See https://github.com/mirage/ocaml-conduit/issues/238, this is fixed on master. I'm trying to make a release, but the [SSL backend](https://github.com/mirage/ocaml-conduit/pull/241) and [launchd](https://github.com/mirage/ocaml-conduit/pull/240) backends are also broken, so I'm also [fixing the CI](https://github.com/ocaml/ocaml-ci-scripts/pull/181) to catch these kind of errors earlier... Hopefully this long journey should be ending soon and a release will happen.

**Comment by hannesm** [comment]
@samoht thanks!  closing this then.  sorry, I didn't see #238 when browsing the issues/PRs, since it is already closed (and I don't `watch` this repository).  Hopefully awaiting a new release really soon now then :)

**Comment by Silur** [comment]
this means that OpenSSL method is no longer supported? only ocaml-tls?
