### ISSUE TITLE
TLS: remote certificate introspection

### ISSUE THREAD

**Issue by xguerin** [mirage/ocaml-conduit#253]
Hello,

I am looking for a way to introspect the certificates of a remote server using `conduit_lwt_unix` (I am interested in CN and SAN). Perusing the documentation I did not find any way to access the TLS state once the connection has been established. Am I looking in the right direction ?

Thanks,

**Comment by dinosaure** [comment]
As #155, it's now possible with the new version of `conduit` to introspect the given `Conduit.flow` and extract from it some information. The code for such request looks like:
```ocaml
Conduit_lwt.resolve ~resolvers domain_name >>= function
| Ok (Conduit_lwt_tls.TCP.T v) ->
  let lwt_socket = Conduit_lwt_tls.underlying v in
  ...
| _ -> ...
```

But as I said, `Conduit_lwt_tls` is poor about accessors. At this stage you will only be able to extract the underlying socket used. If you want some specific accessors to get some information about the underlying TLS state used, feel free to re-open this issue with specific task, I will happy to fill the API with your tasks. Thanks.

**Comment by hannesm** [comment]
Once you have a Tls_lwt.Unix.t at hand, you can use https://mirleft.github.io/ocaml-tls/doc/tls/Tls_lwt/Unix/index.html#val-epoch to retrieve the epoch -- which includes the certificate, TLS version, cipher, etc. used for that session (see https://mirleft.github.io/ocaml-tls/doc/tls/Tls/Core/index.html#type-epoch_data for accessors)

**Comment by xguerin** [comment]
Thanks, I'll take a look 👍
