### ISSUE TITLE
dependency conflict when working with tls

### ISSUE THREAD

**Issue by jotterbach** [mirage/ocaml-conduit#254]
I'm trying to work with cohttp and ssl endpoints that require me to install ocaml-tls. However, when working in utop and importing all requires files I run into an interface conflict between Conduit, tls and Core. 

```The files /Users/johannes/.opam/4.06.0/lib/tls/tls-lwt.cma
and /Users/johannes/.opam/4.06.0/lib/core/core.cma
disagree over interface Core
The files /Users/johannes/.opam/4.06.0/lib/conduit-lwt-unix/conduit_lwt_unix.cma
and /Users/johannes/.opam/4.06.0/lib/core/core.cma
disagree over interface Core
Error: Reference to undefined global `Conduit_lwt_unix```

With pure SSL I run into issues with the v3 handshake. I'm working on MacOSX and ocaml 4.06.0

**Comment by rgrinberg** [comment]
This is a known issue with ocaml-tls https://github.com/mirleft/ocaml-tls/issues/376 there's nothing we can do here unfortunately.
