### ISSUE TITLE
mirage-conduit can't resolve

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-conduit#259]
until recently, all worked smooth -- but a recent update to mirage-conduit 3.0.1, I get the following error while trying to run Canopy: `canopy-store failed pull (Failure "name resolution failed: unknown endpoint type")`

any ideas whether there were remarkable changes?  also it seems that the main conduit got new releases while mirage-conduit didn't - is this intentional?

**Comment by avsm** [comment]
#245?

**Comment by avsm** [comment]
no, that's unix only

**Comment by hannesm** [comment]
cannot reproduce, was stuck in other issues as well... may have just been a "host name resolution failed"?  but the `unknown endpoint type` is weird... closing since i can't reproduce and thus no more debug information :/
