### ISSUE TITLE
Linking, tls and windows

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-conduit#264]
It seems we have a _linking bug_ when we want to have the SSL support on `cohttp`. I really don't know what happens but, on `ocaml-git`, if I want to use `tls`, I did not have any problem on Linux but (cf. mirleft/ocaml-nocrypto#135) I have a problem on Windows.

So, a solution could be "(ssl | tls)" as a dependency of `git-unix` but [neither Travis nor Appveyor is happy](https://github.com/mirage/ocaml-git/pull/277) ... Then, with a little discussion with @samoht, the problem seems to be in `conduit`. So it's why I created this issue.

**Comment by samoht** [comment]
We need to define `tls` as an optional dependency only on non-windows, but I am not sure it is possible with opam 1.2 syntax.
