### ISSUE TITLE
Intermittent "TLS to non-TCP currently unsupported" error on one system

### ISSUE THREAD

**Issue by donut** [mirage/ocaml-conduit#266]
I've built an application on macOS High Sierra and it's been running without issue. However, the production system is a Hackintosh running macOS 10.11.6 (El Capitan). This application makes a lot of requests, and eventually they all start failing with this error. Here is an example:

> Jw_client__Exn.Request_failure("GET", "https://cdn.jwplayer.com/v2/media/5w2NvZtb?cache_break=572246083", "(Failure\n  \"TLS to non-TCP currently unsupported: host=cdn.jwplayer.com endp=(Unknown \\\"name resolution failed\\\")\")")

Looks like this error is originating from [conduit_lwt_unix.ml#L336-L339](https://github.com/mirage/ocaml-conduit/blob/master/lwt-unix/conduit_lwt_unix.ml#L336-L339).

My application is running into it [here](https://github.com/RightThisMinute/OVPSync/blob/master/lib/jw_client/delivery.ml#L24-L26) and [here](https://github.com/RightThisMinute/OVPSync/blob/master/lib/jw_client/platform.ml#L113-L115).

Restarting the application leads to requests working just fine again for a while. My guess is that it has something to do with the server it's running on, not this library. But I thought I'd post here just in case I'm missing something obvious.

**Comment by dinosaure** [comment]
Close to #264 I think

**Comment by donut** [comment]
#264 seems to be mainly Windows focused. I'm not seeing how it's connected, but I'm also very inexperienced in all of this.

**Comment by donut** [comment]
It seems like #264 has to with linking the `tls` package. I've run into this issue both with and without that package installed.

**Comment by dinosaure** [comment]
This kind of dynamic error is not possible anymore with the new design of `conduit` where we decided to explicitly say on what `conduit` depends now (and delete `depopts`). If you want a TCP + TLS connection (mostly to communicate with a website), you probably need the package `conduit-lwt-tls` now (which uses `ocaml-tls`) or `conduit-lwt-ssl` (which uses `ocaml-ssl`).

For example, if you want a way to communicate over TCP + TLS, the code looks like:
```ocaml
let resolve_tls =
  let null ~host:_ _ = Ok None in
  let config = Tls.Config.client ~authenticator:null () in
  Conduit_lwt_tls.TCP.resolve ~port:443 ~config

let resolvers =
  Conduit.empty
  |> Conduit.add ~priority:20 Conduit_lwt.TCP.protocol (Conduit_lwt.TCP.resolve ~port:80)
  |> Conduit.add ~priority:10 resolve_tls

let run domain_name =
  Conduit.resolve ~resolvers domain_name >>= fun flow ->
  ...
```

**Comment by donut** [comment]
Cool, thanks for the update.

**Comment by mseri** [comment]
This should be probably repened for now, since we pulled cohttp 3.0. I have seem this error multiple times in opam-ci builds
