### ISSUE TITLE
Huge GC pressure caused by I/O in Conduit_lwt_unix_ssl

### ISSUE THREAD

**Issue by mfp** [mirage/ocaml-conduit#27]
[`Conduit_lwt_unix_ssl` uses `Lwt_ssl.in_channel_of_descr` and `out_channel_of_descr`](https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_unix_ssl.ml#L27) to create the `Lwt_io` channels it uses. Unfortunately, these use under the hood `Lwt_ssl.read/write_bytes`, [which allocate a string the size of the data being read/written](https://github.com/ocsigen/lwt/blob/master/src/ssl/lwt_ssl.ml#L156).

Adding insult to injury, the default buffer size is 4 KB, well over the 256-word limit for blocks in the minor heap. So the same amount of data being read/written is allocated in the major heap, to become garbage right away. GC pressure increases, lots of mark&sweeping ensues, and on top of it the more frequent minor collections cause even more soon-to-become-garbage data to be promoted.

Refer to https://github.com/ocsigen/ocsigenserver/issues/49 for the consequences of such allocation. See also https://github.com/mirage/ocaml-cohttp/issues/207.

**Comment by rgrinberg** [comment]
@mfp Shouldn't this be a ticket in `Lwt_ssl.{read,write}_bytes`?

To my untrained eye, can't you just pass the buffer to `{read,write}_bytes` before the `Lwt_io.make`. It's still not ideal as you're doing the copying `Ssl.read -> buffer -> Lwt_bytes`

**Comment by mfp** [comment]
I must confess this issue exists mainly to give more visibility to the
actual allocation/copying issues in Lwt_ssl/ocaml-ssl :)

Hopefully, https://github.com/savonet/ocaml-ssl/pull/15 will be accepted
eventually (AFAIK there's nothing holding it back besides hmm lack of time?)
and then we will be able to address https://github.com/ocsigen/lwt/issues/98
and close all the issues recursively.

**Comment by dinosaure** [comment]
savonet/ocaml-ssl#15 is merged/released and `conduit.3.0.0` properly uses `Lwt_ssl.{read/write}_bytes` to avoid the memory pressure. It's hard to really say/prove that `conduit.3.0.0` fixes the problem - however, we can say that the new release was aware about this problem. I will close the issue but, if you still have the problem, you are free to re-open it.
