### ISSUE TITLE
Is IPv6 supported only client-side?

### ISSUE THREAD

**Issue by vog** [mirage/ocaml-conduit#270]
The mirage website states that mirage supports IPv6. However, from the docs and function signatures it seems that this statement applies only to client-side, not server-side.

Having a look at the `Conduit_lwt_unix` documention (https://docs.mirage.io/conduit-lwt-unix/Conduit_lwt_unix/index.html), there is the following description:

```
`TCP (`Port port): Listen on the specified TCPv4 port.
```

So, what is the current state of IPv6 for the server API?

**Comment by avsm** [comment]
For now, I think it's client side only. Our ipv6 support has really moved in fits and starts, just because of the difficulty of testing it.  Nowadays however, there are lots of providers giving us access, so it's a matter of just implementing the last glues between the stack.

**Comment by dinosaure** [comment]
This issue becomes orthogonal to `conduit` when it's not the responsibility of `conduit` to care about TCP/IPv6 protocol implementation - but something else like the host's TCP/IPv6 stack or `mirage-tcpip` (which should have soon the IPv6 support). Then, feel free to _register_ the protocol implementation into `conduit`.

`conduit-lwt` provides such implementation (and it uses the host's TCP/IPv6 stack), so it is able to handle IPv6 connection. To ensure to communicate with an IPv6, this code should works:
```ocaml
let my_resolver domain_name = match Unix.getaddrinfo (Domain_name.to_string domain_name) "tcp" Unix.[ AI_SOCKTYPE PF_INET6 ] with
  | [] -> Lwt.return_none
  | x :: _ -> Lwt.return_some x.Unix.ai_addr
  | exception _ -> Lwt.return_none

let resolvers =
  Conduit.empty
  |> Conduit_lwt.add Conduit_lwt.TCP.protocol my_ipv6_resolver

let run domain_name =
  Conduit.resolve ~resolvers domain_name >>= fun flow ->
  ...
```

**Comment by hannesm** [comment]
for the common use of a dual stack listener (IPv4 and IPv6), there's a bit more to do here (on unix): the `let fd = Lwt_unix.socket PF_INET6 ... ` creates a IPv6 socket. On some (dual-stack) Unix systems this is sufficient for accepting both IPv4 and IPv6 connections, on others there's need to call `Lwt_unix.(setsockopt fd IPV6_ONLY false)`.

If I read the current implementation correctly (Conduit_lwt.init), there's no way to pass this socket option. I propose to extend "type configuration" with a `v6_only : bool` field, and call the setsockopt unconditionally. Furthermore, I'd suggest to add a constructor function for configuration (i.e. `let configuration ?(sockaddr = Unix.inet6_addr_any) ?(capacity = 40) ?(v6_only = false) () = { sockaddr ; capacity ; v6_only }`). It is not clear just from the sockaddr being used whether it should be a v6 only or a dual v4 and v6 listening socket.

**Comment by dinosaure** [comment]
Hmmhm, I see your point, I will open an issue about this specific point.
