### ISSUE TITLE
Unable to bind server to specific IP address

### ISSUE THREAD

**Issue by vog** [mirage/ocaml-conduit#271]
I noticed that it is only possible for a TCP server to open the port on all IP addresses. There is no possibility to bind just to a specific IP address.

In case this functionality is not desired and has been left out on purpose: Why is that?

For example, when running a web service on a developer's computer, it is more common to bind it to 127.0.0.1:8000 than to 0.0.0.0:8000.

(Of course, one should expect a good developer to have some firewall rules in place anyway, and one should expect a good OS/distro to deploy such rules by default. Still, binding to 0.0.0.0 by default makes me uneasy.)

**Comment by dinosaure** [comment]
The new version of `conduit` deleted the resolution part when we want to _launch_ a server. A concrete value is needed now, depending on your service, to launch a server. For example, for a simple TCP server, you should do:
```ocaml
let tcp_config =
  { Conduit_lwt.TCP.sockaddr= Ipaddr_unix.to_inet_addr (Ipaddr.of_string "127.0.0.1") (* or Unix.inet_addr_loopback directly *)
  ; capacity= 40 }

let run =
  let _stop, loop = Conduit_lwt.serve ~service:Conduit_lwt.TCP.service tcp_config in
  loop
```
