### ISSUE TITLE
The latest dune-release tarball has an inconsistent naming scheme.

### ISSUE THREAD

**Issue by Zimmi48** [mirage/ocaml-conduit#278]
All recent releases come with a `conduit-1.x.x.tbz` dune-release tarball except the latest one which comes with a `conduit-v1.3.0.tbz` tarball. For package managers, this inconsistency is quite annoying. Could you fix the problem by uploading a copy of `conduit-v1.3.0.tbz` named `conduit-1.3.0.tbz`? (Removing the existing tarball is probably not a good idea in case someone is already relying on it.)
Thanks!

**Comment by djs55** [comment]
I've uploaded `conduit-1.3.0.tbz`. Thanks for your report!

**Comment by Zimmi48** [comment]
Thanks a lot!
