### ISSUE TITLE
"Just OpenSSL for now"

### ISSUE THREAD

**Issue by rneswold** [mirage/ocaml-conduit#299]
Why does the ```README.md``` file say this library only works with OpenSSL and then, in the next paragraph, it discusses how to enable native TLS support (which I believe doesn't use OpenSSL)?

**Comment by yomimono** [comment]
I believe this is supposed to mean "just OpenSSL, not BoringSSL or LibreSSL or MatrixSSL or..." from the possible set of C bindings, as opposed to the OCaml-native TLS library.  I agree it's rather unclear as stated, though.

**Comment by rneswold** [comment]
Okay. Thanks for the interpretation.
