### ISSUE TITLE
Conduit.S.PROTOCOL does not exists

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-conduit#356]
I'm not sure if it's a nice idea to use the trick about `_intf` because, currently we can introspect `conduit.mli` and see `Conduit.S.PROTOCOL` but we can not re-use it:
```sh
$ ocaml
# #show Conduit.S.PROTOCOL ;;
Unknown element.
# 
```

Any idea @samoht?

**Comment by avsm** [comment]
Shouldn't that be `#show_module_type` ?

**Comment by dinosaure** [comment]
> Shouldn't that be #show_module_type ?

The error is just more precise than a call with `#show`.

**Comment by CraigFe** [comment]
Unfortunately, OCaml top-level and Odoc aren't quite clever enough about resolving aliases (and the `@inline` annotation applies to inclusions only, not aliases). So we have:

### Bad

```ocaml
module type S = Conduit_intf.S
(** @inline *)
```

### Good

```ocaml
module type S = sig
  include Conduit_intf.S
  (** @inline *)
end
```

I'll prepare a patch.

**Comment by CraigFe** [comment]
Should be resolved by https://github.com/mirage/ocaml-conduit/pull/357.

**Comment by avsm** [comment]
cc @jonludlam on this -- this seems like something to fix in odoc as well.

**Comment by CraigFe** [comment]
I believe this is already fixed in Odoc (2.0+), which expands aliases to hidden modules rather than generating documentation for them. So once we're using the new model, the above examples will be equivalent to just:

```ocaml
module type S = Conduit_intf.S
```

@jonludlam may wish to correct me on this.

**Comment by avsm** [comment]
So to fix this without codesmell in our interfaces, we also need to apply the odoc model resolver to the toplevel, by the sounds of it.

**Comment by dinosaure** [comment]
I'm not sure that #357 is the right direction when this simple code can not compile:
```ocaml
let _ = match Conduit_lwt.Service.equal Conduit_lwt.TCP.service Conduit_lwt.TCP.service with
  | Some (Conduit_lwt.Refl, _, _) -> ()
  | _ -> ()
```

**Comment by dinosaure** [comment]
#361 re-fix/re-export the `Refl` constructor to be usable outside of Conduit.
