### ISSUE TITLE
ipaddr-sexp not included in conduit-async dune file

### ISSUE THREAD

**Issue by sgrove** [mirage/ocaml-conduit#384]
It seems that there's likely a missing dependency in `conduit-async` dune file for the `ipaddr-sexp` lib - the change here seems to fix it in our project: https://github.com/anmonteiro/ocaml-conduit/commit/4d1cc3f9988e6f705c672969bb7b96342cd8f305

**Comment by dinosaure** [comment]
Fixed by #385, we will cut a release as soon as we can :+1:, thanks!
