### ISSUE TITLE
Conduit_mirage: make TLS dependency optional 

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-conduit#39]
From @talex5: 

> It would be good to make the config type abstract, so that conduit doesn't bring in dependencies on the TLS libraries.

**Comment by samoht** [comment]
Not sure how to do this properly: how do you build `Tls.Config.{server,client}` values if you make the type abstract?

We already do that for `Conduit.endp` and I'm not sure that's a good idea (actually we don't really abstract the type, we just badly abstract the upstream types)

**Comment by talex5** [comment]
Could we move the type `Conduit_mirage.server` inside `S`? Then the final functor would be something like:

    module Make(S:V1_LWT.STACKV4)(V: VCHAN_PEER)(T:TLS) :
      S with type stack = S.t
         and type peer = V.t
         and type tls_config_server = T.Config.server

**Comment by samoht** [comment]
@talex5 good idea. Tentative implementation in #51 A nice side-effect of that is that `vchan` is not a really a dependency anymore (ie. it's easy to add a `No_Vchan` module as you did with `No_TLS`).

I need to update the mirage tool to check that it works fine, but I quite like the refactoring.

**Comment by hannesm** [comment]
see also https://github.com/mirage/mirage/issues/543

**Comment by dinosaure** [comment]
According to the new version of `conduit`, `ocaml-tls` is no longer a dependency of `conduit-mirage`/`conduit-lwt`/`conduit-async` (to use `ocaml-tls`, you must use `conduit-{lwt,async}-tls`). The new version comes with an _abstract_ configuration value needed to initialize a connection and finally `conduit` (core) does not bring any dependencies such `ocaml-tls`/`ocaml-ssl`/etc.
