### ISSUE TITLE
Have a Channel backend for Cohttp with raw Request/Response

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-conduit#40]
Requested by @talex5 and @pqwy :

> It might be nice if mirage would let you configure an HTTP server without using conduit. Resolving URLs needs to be dynamic, but when providing a service you usually know statically which transport you want (http, https or vchan).

**Comment by dinosaure** [comment]
According to the new version of `conduit`, the initialization of a server does not require the dynamic resolution provided before by `conduit`. A service can be initialized as is with static values such as:
```ocaml
let tcp_cfg =
  { sockaddr= Unix.(ADDR_INET (inet_addr_any, 80))
  ; capacity= 40 }

let run =
  let _stop, loop = Conduit.serve ~handler ~service:Conduit_lwt.TCP.service tcp_cfg in
  loop
```
