### ISSUE TITLE
Binding on Unix to particular IP not working

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-conduit#42]
Using `cohttp-server-lwt` it appears to bind to all interfaces even with a specific `-s`

**Comment by samoht** [comment]
Seems that `cohttp-server-lwt` doesn't call the conduit init function -- actually it does nothing at all with the `host` parameter:

https://github.com/avsm/ocaml-cohttp/blob/master/bin/cohttp_server_lwt.ml#L92

**Comment by samoht** [comment]
I've moved the issue in cohttp's bugtracker.
