### ISSUE TITLE
`Resolver_mirage.register` should not overwrite the resolver's service

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-conduit#44]
Currently, `Resolver_mirage.register` do some stuff to register the DNS functions and then it calls:

```ocaml
      Resolver_lwt.set_service ~f:static_service res;
```

which reset the services of `res`. This is annoying if you are in an unikernel and want to add some services which are not very common (and thus are not defined in the static `Uri_services`).

**Comment by avsm** [comment]
Agreed
