### ISSUE TITLE
with vchan results in surprising symbol error on Unix

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-conduit#74]
conduit 0.8.3 and vchan 2.0.2:

```
# #require "conduit.lwt-unix";;
Error: The external function `stub_evtchn_virq_dom_exc' is not available
```

This error occurs when trying to use any dependent library (and does not have an obvious cause) and is problematic for no-switch development of Mirage applications. Some kind of configurations, dummy stub, or stub-with-an-error-message-name would be helpful.

**Comment by samoht** [comment]
do you have the error with trunk (ie. 0.8.4)? I'm still in the process of releasing everything, I'm almost there (I'm waiting for https://travis-ci.org/mirage/mirage-skeleton/builds/64898666).

**Comment by dsheets** [comment]
Present in 0a9d08cd07d0ae4456f2b92aab2170ff6be0f712 (master now).

**Comment by samoht** [comment]
Do you have vchan installed?

**Comment by dsheets** [comment]
Yes, vchan 2.0.2.

**Comment by samoht** [comment]
I'm trying to repro this. Meanwhile you can simply uninstall vchan (which is not anymore a hard dep)

**Comment by samoht** [comment]
wait, wait: `#require "conduit.lwt-unix";;` this has nothing to do with `mirage.conduit` so I'll check if I see how to fix it.

**Comment by samoht** [comment]
Moved the discussion upstream: https://github.com/mirage/ocaml-evtchn/issues/20
