### ISSUE TITLE
Getting IP address from Client that connected. 

### ISSUE THREAD

**Issue by fxfactorial** [mirage/ocaml-conduit#87]
I'm trying to get the IP address of a client that connected to a conduit powered server. 

I have a Conduit_lwt_unix.flow object, which I've tried working with:

```ocaml
  let address = match ch with
    | Conduit_lwt_unix.TCP g -> Some (g.Conduit_lwt_unix.ip |> Ipaddr.to_string)
    | _ -> None
```

but this string appears to be the address of the server. I've also tried playing with the numerous `Conduit_lwt_unix.sexp_*` functions but some of these just hang and others don't return fruitful information. Any simple self-contained code sample is much appreciated.

**Comment by avsm** [comment]
Some hang? That's definitely not the right behaviour :-)  I'm at LinuxCon at the moment but have queued up to take a look at this shortly if wifi permits...

**Comment by avsm** [comment]
(If you have a small standalone test case that would be very helpful)

**Comment by fxfactorial** [comment]
@avsm Still need to find my hanging example but now I have an even better one. This doesn't hang, nor does it throw any exception, just says `Error: Internal Server Error`

```ocaml
#require "cohttp.lwt"

open Conduit_lwt_unix

let callback (ch, conn) req body =
  begin match ch with
    | TCP g ->
      begin match sexp_of_tcp_flow g |> client_of_sexp with
        | `TCP (`IP c, _) -> c |> Ipaddr.to_string |> print_endline
        | _ -> ()
      end
    | _ -> ()
  end;
  Cohttp_lwt_unix.Server.respond_string ~status:`OK ~body:"Nice job" ()

let this_server =
  Cohttp_lwt_unix.Server.make ~callback ()
  |> Cohttp_lwt_unix.Server.create

let () =
  Lwt_main.run this_server
```

It seemed like a reasonable program to me...

I don't understand the utility of these Sexp functions and whatnot. Are they in effect side stepping the type system?

**Comment by rgrinberg** [comment]
The error that your'e getting is an sexp conversion error because the conversion that you're trying to do is incorrect. You don't get a better error message because of https://github.com/mirage/ocaml-cohttp/pull/402. We should definitely re-enable optional logging in this situation. It's on my todo list.

Please try the following snippet and see if it fixes your problem:

```ocaml
#require "cohttp.lwt"

open Conduit_lwt_unix
open Cohttp_lwt_unix

let callback (ch, conn) req body =
  match ch with
  | TCP g ->
    begin match Conduit_lwt_unix.endp_of_flow ch with
    | `TCP (ip, port) ->
      Server.respond_string ~body:(Ipaddr.to_string ip) ~status:`OK ()
    | _ -> assert false
    end
  | _ -> assert false

let this_server =
  Cohttp_lwt_unix.Server.make ~callback ()
  |> Cohttp_lwt_unix.Server.create ~mode:(`TCP (`Port 8000))

let () =
  Lwt_main.run this_server
#require "cohttp.lwt"

open Conduit_lwt_unix
open Cohttp_lwt_unix

let callback (ch, conn) req body =
  match ch with
  | TCP g ->
    begin match Conduit_lwt_unix.endp_of_flow ch with
    | `TCP (ip, port) ->
      Server.respond_string ~body:(Ipaddr.to_string ip) ~status:`OK ()
    | _ -> assert false
    end
  | _ -> assert false

let this_server =
  Cohttp_lwt_unix.Server.make ~callback ()
  |> Cohttp_lwt_unix.Server.create ~mode:(`TCP (`Port 8000))

let () =
  Lwt_main.run this_server
```

**Comment by fxfactorial** [comment]
Here's what happened.

![conduit_issues](https://cloud.githubusercontent.com/assets/3036816/9335706/6dc481ae-458a-11e5-89eb-8db033ec534e.gif)

Surely the address is incorrect

**Comment by avsm** [comment]
This was a bug in Conduit_lwt_unix that should be fixed in #90.  With that patch, the callback `flow` argument is the client connection and not the server one.

**Comment by fxfactorial** [comment]
Just tested, works. Thank you.

**Comment by dsheets** [comment]
@fxfactorial when you edit a comment, no new email is sent so maybe @avsm doesn't know.

Are you saying that the port reported is not the client port?

**Comment by avsm** [comment]
@fxfactorial thats reporting the client port that it connected on.  With TCPv4, the server has a IP/port and the client has a source IP/port.  So in this case, the TCP connection was from client-ip:3148 to server-ip:8080.  Does that make sense?  Since the server already knows what port it is listening on, you only want the client IP/source port in the logging callback.

**Comment by fxfactorial** [comment]
@avsm Makes sense, much appreciated.
