### ISSUE TITLE
Handle connection to IPv6 link local addresses

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-conduit#9]
For a project I need to connect to link-local IPv6 addresses.
As this is not possible under normal OCaml Unix, I wrote another binding to the necessary unix primitives using Ctypes, here: http://github.com/vbmithr/ocaml-sockopt.

Now I'd like irminsule to fetch data from an IPv6 link local address, and irminsule uses cohttp for that, which in turn uses ocaml-conduit.

So I'm asking what is in your opinion the best/cleanest way to achieve this.
The first thing I'm thinking about is to hack ocaml-conduit to plumb it into my ocaml-sockopt library but if I'm working on that, I'd better have in integrated. So what do you think ?

**Comment by samoht** [comment]
> I definitely want to support this use case; will be refreshing conduit patches this afternoon i hope

long afternoon! :p would be nice if `Conduit_mirage.Make_flow` could just take a `V1_LWT.TCP` instead of `TCPV4`.

**Comment by dinosaure** [comment]
From the new version of `conduit`, it is possible to give an IPv6 to the `connect` function (implemented by the `Flow` module). Then, with #322, a concrete endpoint can be an IPv6 value. In these ways, we can consider that this issue is fixed... 5 fives after (a long long afternoon).
